# remote_theme: rundocs/jekyll-rtd-theme
#remote_theme: readthedocs/sphinx_rtd_theme    #just-the-docs/just-the-docs
remote_theme: potigol/jekyll-theme-rtd

readme_index:
  with_frontmatter: true
  
#theme: jekyll-theme-leap-day

translate:
  # shortcodes
  danger: Perigo
  #note:
  tip: Dica
  warning: Atenção
  # 404
  #not_found:
  # copyright
  revision: Revisão
  # search
  #searching:
  #search:
  search_docs: Pesquisar
  search_results: Resultado da pesquisa 
  #search_results_found: # the "#" in this translate will replaced with results size!
  #search_results_not_found:
